Peravia/urls.py
from django.conf.urls import patterns, include, url


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()
from django.conf import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Peravia.views.home', name='home'),
    # url(r'^Peravia/', include('Peravia.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    #url(r'^', include('agenda.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^encuestas/', include('polls.urls', namespace='polls')),
    url(r'^', include(admin.site.urls)),

    (r'', include('django.contrib.auth.urls')),
    url(r'^chaining/', include('smart_selects.urls')),

)

if settings.DEBUG:
    urlpatterns += patterns('django.contrib.staticfiles.views',
                            url(r'^static/(?P<path>.*)$', 'serve',{'document_root':settings.STATIC_ROOT}),
                            )

polls/urls.py
__author__ = 'Yusdenis'

from django.conf.urls import  patterns, url

from polls  import  views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^(?P<poll_id>\d+)/(?P<client_id>\d+)$', views.create, name='create'),
    url(r'^lista/(?P<poll_id>\d+)$', views.polls, name='polls'),
)

polls/models.py
from django.db import models
from django.utils import  timezone
from django.contrib.auth.models import User
from clientes.models import Cliente

class Encuesta(models.Model):
    etiqueta = models.CharField(max_length=100)
    texto = models.TextField(blank=False)
    def __unicode__(self):
        return self.etiqueta
    class Meta:
        verbose_name= 'Encuesta'
        verbose_name_plural = 'Encuestas'

class Pregunta(models.Model):
    texto = models.TextField(blank=False)
    # Una pregunta es simple cuando la seleccion es de una sola respuesta
    simple = models.BooleanField(default=True)
    # Permite_add es para si en la parte de abajo de la pregunta se puede escribir
    permite_add = models.BooleanField(default=False)
    encuesta = models.ForeignKey(Encuesta, related_name='preguntas')

    def __unicode__(self):
        return  unicode(self.encuesta)+' - '+ self.texto

    class Meta:
        verbose_name= 'Pregunta'
        verbose_name_plural = 'Preguntas'


class PosibleRespuesta(models.Model):
    texto = models.CharField(max_length=250, blank=False, null= False)
    pregunta = models.ForeignKey(Pregunta, related_name='posibles')
    def __unicode__(self):
        return self.texto

class Respuesta(models.Model):
    texto = models.TextField(blank=True, null=True)
    pregunta = models.ForeignKey(Pregunta, related_name='respuestas')
    encuesta = models.ForeignKey(Encuesta, null=True)
    user = models.ForeignKey(User, null= True, blank=True)
    cliente = models.ForeignKey(Cliente, null= True)
    creada = models.DateTimeField(auto_now=True, default = timezone.now())


class OpcionElegida(models.Model):
    elegida = models.ForeignKey(PosibleRespuesta)
    respuesta = models.ForeignKey(Respuesta, related_name='elegidas')

polls/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import  render, get_object_or_404
from polls.models import  Encuesta, Respuesta, Pregunta, PosibleRespuesta, OpcionElegida
from clientes.models import Cliente
from django.contrib import  messages

def index(request):
    encuestas = Encuesta.objects.all()
    return render(request,'polls/index.html',{'encuestas': encuestas})

@login_required()
def create(request, poll_id, client_id):
    encuesta = get_object_or_404(Encuesta, pk=poll_id)
    if(int(client_id) == 0):
        clientes = Cliente.objects.all().order_by('nombre')
    else:
        clientes = Cliente.objects.filter(pk=client_id).order_by('nombre')
        cliente = Cliente.objects.get(pk=client_id)
    posibles = []
    textos = {}
    if request.method == 'POST':
        respuestas = getDictArray(request.POST, poll_id)
        cliente = Cliente.objects.get(pk=request.POST.get('cliente_id'))
        for k,respuesta in respuestas.iteritems():
            # buscando la respuesta asociada a la pregunta
            p = Pregunta.objects.get(pk=k, encuesta__id = poll_id)
            if p:
                r = Respuesta.objects.filter(pregunta__id = p.id, cliente__id = cliente.id)[:1]
                if r:
                    r = r[0]
                    r.elegidas.all().delete()
                else:
                    r = Respuesta.objects.create(pregunta = p)
                elegidas = PosibleRespuesta.objects.filter(id__in = request.POST.getlist(poll_id+"["+str(k)+"]"+"[choice]") )
                if respuesta.has_key("add"):
                    r.texto = respuesta["add"]
                else:
                    r.texto = ''
                for elegida in elegidas:
                    opcion = OpcionElegida(elegida = elegida, respuesta = r)
                    r.elegidas.add(opcion)
                r.user = request.user
                r.cliente = cliente
                r.encuesta = encuesta
                r.save()
                messages.success(request, 'Encuesta almacenada satisfactoriamente.')
    try:
        preguntas = encuesta.preguntas.all()
        if cliente:
            for pregunta in preguntas:
                respuesta = Respuesta.objects.filter(pregunta__id = pregunta.id, cliente__id = cliente.id)[:1]
                if respuesta:
                    respuesta = respuesta[0]
                    for elegida in respuesta.elegidas.all():
                        posibles.append(elegida.elegida.id)
                    textos[respuesta.pregunta.id] = respuesta.texto
    except:
        pass
    return render(request, 'polls/create.html',
        {'encuesta': encuesta,'clientes':clientes,'client_id': int(client_id), 'elegidas':posibles,'textos':textos})


@login_required()
def polls(request, poll_id):
    encuesta = get_object_or_404(Encuesta, pk=poll_id)
    respts = Respuesta.objects.filter(encuesta__id = poll_id).order_by('creada')
    rids, respuestas = [],[]
    for r in respts:
        if r.cliente.id not in rids:
            rids.append(r.cliente.id)
            respuestas.append(r)
    return render(request, 'polls/polls.html', {'respuestas': respuestas, 'encuesta': encuesta})

def getDictArray(post, name):
    dic = {}
    for k in post.keys():
        if k.startswith(name):
            rest = k[len(name):]

            # split the string into different components
            parts = [p[:-1] for p in rest.split('[')][1:]
            print parts
            id = int(parts[0])

            # add a new dictionary if it doesn't exist yet
            if id not in dic:
                dic[id] = {}

            # add the information to the dictionary
            dic[id][parts[1]] = post.get(k)
    return dic

templates/polls/base.html
{% load i18n staticfiles%}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
<title>{% block title %}{% endblock %}</title>
{% block stylesheet %}
   <link rel="stylesheet" type="text/css" href="{% static "admin/css/base.css" %}" />
{% endblock %}


{% block extrastyle %}{% endblock %}
<!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="{% block stylesheet_ie %}{% static "admin/css/ie.css" %}{% endblock %}" /><![endif]-->
{% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% block stylesheet_rtl %}{% static "admin/css/rtl.css" %}{% endblock %}" />{% endif %}
<script type="text/javascript">window.__admin_media_prefix__ = "{% filter escapejs %}{% static "admin/" %}{% endfilter %}";</script>
{% block extrahead %}{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
</head>
{% load i18n %}

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}">

<!-- Container -->
<div id="container">
    {% if not is_popup %}
    <!-- Header -->
    <div id="header">
        <div id="branding">
        {% block branding %}{% endblock %}
        </div>
        {% if user.is_active and user.is_staff %}
        <div id="user-tools">
            {% trans 'Welcome,' %}
            <strong>{% filter force_escape %}{% firstof user.get_short_name user.get_username %}{% endfilter %}</strong>.
            {% block userlinks %}
                {% url 'django-admindocs-docroot' as docsroot %}
                {% if docsroot %}
                    <a href="{{ docsroot }}">{% trans 'Documentation' %}</a> /
                {% endif %}
                {% if user.has_usable_password %}
                <a href="{% url 'admin:password_change' %}">{% trans 'Change password' %}</a> /
                {% endif %}
                <a href="{% url 'admin:logout' %}">{% trans 'Log out' %}</a>
            {% endblock %}
        </div>
        {% endif %}
        {% block nav-global %}{% endblock %}
    </div>
    <!-- END Header -->
    {% block breadcrumbs %}
    <div class="breadcrumbs">
    <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
    {% if title %} &rsaquo; {{ title }}{% endif %}
    </div>
    {% endblock %}
    {% endif %}

    {% block messages %}
        {% if messages %}
        <ul class="messagelist">{% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}</ul>
        {% endif %}
    {% endblock messages %}

    <!-- Content -->
    <div id="content" class="{% block coltype %}colM{% endblock %}">
        {% block pretitle %}{% endblock %}
        {% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}
        {% block content %}
        {% block object-tools %}{% endblock %}
        {{ content }}
        {% endblock %}
        {% block sidebar %}{% endblock %}
        <br class="clear" />
    </div>
    <!-- END Content -->

    {% block footer %}<div id="footer"></div>{% endblock %}
</div>
<!-- END Container -->

</body>
</html>

templates/polls/base_site.html
{% extends "admin/base.html" %}
{% load i18n %}

{% block title %}{{ title }} | {% trans 'Peravia site admin' %}{% endblock %}




{% block branding %}
<h1 id="site-name">{% trans 'Peravia administracion' %}</h1>
{% endblock %}

{% block extrahead %}
{% endblock %}

{% block nav-global %}{% endblock %}

templates/polls/create.html
{% extends "polls/base.html" %}
{% load i18n static polls_extra%}

{% block extrastyle %}{{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/dashboard.css" %}" />
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />
{% endblock %}

{% block title %}{{ encuesta.etiqueta }} | {{ encuesta.texto }}{% endblock %}

{% block branding %}
    <h1 id="site-name">{% trans 'Peravia administracion' %}</h1>
{% endblock %}

{% block extrahead %}
{% endblock %}

{% block nav-global %}{% endblock %}
{% block coltype %}colM{% endblock %}

{% block bodyclass %}dashboard{% endblock %}

{% if not is_popup %}
    {% block breadcrumbs %}
        <div class="breadcrumbs">
            <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
            &rsaquo;
            <a href="/polls/">Polls</a>
            &rsaquo;
            <a href="/encuestas/">{% trans 'Encuestar Clientes' %}</a>
            &rsaquo;
            {% trans 'Encuestar' %}
        </div>
    {% endblock %}
{% endif %}

{% block content %}
    <div id="content-main">
    <h1>&nbsp;</h1>
        {%  if clientes|length == 0 %}
        <p class="errornote">
            {%   trans 'No hay clientes para encuestar' %}
        </p>
        {% else %}
        <form action="{% url 'polls:create' encuesta.id client_id %}" method="POST" accept-charset="utf-8">{% csrf_token %}
        <input type="hidden" name="encuesta_id" value="{{ encuesta.id }}">
        <div class="module">
            <div class="encuesta">
                {{ encuesta.etiqueta }} &rsaquo; {{ encuesta.texto }}
            </div>
            <div class="form-row">
                <div>
                    <label for="cliente_id" style="font-weight: bold">{% trans 'Cliente' %}: </label>
                    <select name="cliente_id" id="cliente_id">
                        {% for cliente in clientes %}
                            <option value="{{ cliente.id }}" {% if client_id == cliente.id %} selected="selected" {% endif %} >{{ cliente }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            {{ respuesta }}
            {% for pregunta in encuesta.preguntas.all %}
                <div class="pregunta">
                    {{ pregunta.texto    }}
                </div>
                {% if pregunta.posibles.all|length > 0 %}
                    <div class="form-row">
                    <select name="{{ encuesta.id }}[{{ pregunta.id }}][choice]" {% if not pregunta.simple  %}multiple="multiple" size="{{ pregunta.posibles.count }}" {% endif %}>
                        {% for posible in pregunta.posibles.all %}
                            <option value="{{ posible.id }}" {% if elegidas|contiene:posible.id %}selected="selected" {% endif %}>{{ posible.texto }}</option>
                        {% endfor %}
                    </select>
                    </div>
                {% endif %}
                {% if pregunta.posibles.all|length == 0 or pregunta.permite_add %}
                    <div class="form-row">
                    <textarea name="{{ encuesta.id }}[{{ pregunta.id }}][add]" >{{  textos|texto:pregunta.id }}</textarea>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
            <div class="submit-row">
                <input type="submit" name="_save" class="default" value="Grabar">
            </div>
        </form>
        {% endif %}
    </div>
{% endblock %}

templates/polls/index.html
{% extends "polls/base.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/dashboard.css" %}" />{% endblock %}

{% block title %}{% trans 'Encuestas' %} | {% trans 'Peravia site admin' %}{% endblock %}

{% block branding %}
    <h1 id="site-name">{% trans 'Peravia administracion' %}</h1>
{% endblock %}

{% block extrahead %}
{% endblock %}

{% block nav-global %}{% endblock %}
{% block coltype %}colM{% endblock %}

{% block bodyclass %}dashboard{% endblock %}

{% if not is_popup %}
    {% block breadcrumbs %}
        <div class="breadcrumbs">
            <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
            &rsaquo;
            <a href="/polls/">Polls</a>
            &rsaquo;
            {% trans 'Encuestar Clientes' %}
        </div>
    {% endblock %}
{% endif %}

{% block content %}
    <div id="content-main">
        <h1>&nbsp;</h1>
        <div class="module">
            <table>
                <caption>
                    <a title="{% trans 'Encuestar Clientes' %}" class="section" href="">
                        {%  trans 'Listado de Encuestas' %}
                    </a>
                </caption>

                <tbody>
                {% for encuesta in encuestas %}
                <tr>
                    <th scope="row" style="width: 0px">{{ encuesta.etiqueta }}</th>
                    <td style="width: 100%">{{ encuesta.texto }}</td>
                    <td><a class="addlink" href="{% url 'polls:create' encuesta.id 0 %}">{% trans 'Encuestar' %}</a></td>
                    <td><a  href="{% url 'polls:polls' encuesta.id %}">{% trans 'Encuestas Realizadas' %}</a></td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/polls/polls.html
{% extends "polls/base.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/dashboard.css" %}" />{% endblock %}

{% block title %}{% trans 'Encuestas' %} | {% trans 'Peravia site admin' %}{% endblock %}

{% block branding %}
    <h1 id="site-name">{% trans 'Peravia administracion' %}</h1>
{% endblock %}

{% block extrahead %}
{% endblock %}

{% block nav-global %}{% endblock %}
{% block coltype %}colM{% endblock %}

{% block bodyclass %}dashboard{% endblock %}

{% if not is_popup %}
    {% block breadcrumbs %}
        <div class="breadcrumbs">
            <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
            &rsaquo;
            <a href="/polls/">Polls</a>
            &rsaquo;
            {% trans 'Encuestas Realizadas' %}
        </div>
    {% endblock %}
{% endif %}

{% block content %}
    <div id="content-main">
        <h1>&nbsp;</h1>
        <div class="module">
            <table>
                <caption>
                    <a title="{{ encuesta }}" class="section" href="">
                        {{ encuesta }}: {{ encuesta.texto }}
                    </a>
                </caption>

                <tbody>
                {% for respuesta in respuestas %}
                <tr>
                    <th scope="row" >{{ respuesta.cliente }}</th>
                    <td style="width: 100%">&nbsp;</td>
                    <td><a class="changelink" href="{% url 'polls:create' encuesta.id  respuesta.cliente.id %}">{% trans 'Actualizar' %}</a></td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}